# Generated by Django 4.1.3 on 2022-12-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        default=" ", max_length=100, verbose_name="Nombre"
                    ),
                ),
                (
                    "apellido",
                    models.CharField(
                        default=" ", max_length=100, verbose_name="Apellido"
                    ),
                ),
                ("email", models.EmailField(max_length=150, verbose_name="Email")),
            ],
        ),
    ]
