# Generated by Django 4.1.3 on 2022-12-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_formadepagocliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormaDePagoCliente',
        ),
    ]
