# Generated by Django 4.1.3 on 2022-12-06 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(default=' ', max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='PagoForma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=100, verbose_name='Forma de Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_venta', models.DateField(verbose_name='Fecha de Venta')),
                ('monto', models.IntegerField(default=0, verbose_name='Monto')),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('pagoformas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pagoforma')),
            ],
        ),
        migrations.AddField(
            model_name='pagoforma',
            name='clientes',
            field=models.ManyToManyField(through='ventas.Venta', to='ventas.cliente'),
        ),
    ]
