# Generated by Django 4.1.3 on 2022-12-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_formadepagocliente'),
        ('formasdepago', '0001_initial'),
        ('ventas', '0002_alter_venta_clientes_alter_venta_pagoformas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='clientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='ID del cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='pagoformas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formasdepago.pagoforma', verbose_name='ID de la Forma de Pago'),
        ),
    ]
