# Generated by Django 4.1.3 on 2022-12-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_clientes_alter_venta_pagoformas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Dpto')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='departamentos',
            field=models.ManyToManyField(to='ventas.departamento', verbose_name='ID del Departamento'),
        ),
    ]
