# Generated by Django 4.1.3 on 2022-12-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_departamento_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='nombre',
        ),
    ]
