# Generated by Django 4.1.3 on 2022-12-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_remove_departamento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre del Dpto'),
        ),
    ]
