# Generated by Django 4.1.3 on 2022-12-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_venta_clientes_alter_venta_departamentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
